name: Verify Changes

on:
  push:
    branches:
      - 'stable'
      - 'main'
  pull_request:
    branches:
      - 'stable'
      - 'main'

jobs:
  check-forks:
    name: check-forks
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.1.0
        with:
          submodules: recursive

      - name: Check for Forked Branches
        run: ./.github/scripts/check-forked-repos.sh

  verify-gomod:
    name: verify-gomod
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.1.0
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: './go.mod'
          cache-dependency-path: |
              actions/go.sum
              go.sum

      - name: Go Version
        run: go version
    
      - name: Generate Golang
        run: |
          export PATH=$PATH:/home/runner/go/bin/

      - name: Verify Go Mod
        run: ./.github/scripts/check-gomod.sh

      - name: Build Packages
        run: ./.github/scripts/go-build.sh

  verify-golangci-lint:
    name: verify-changes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.1.0
        with:
          submodules: recursive

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          # Patch version isn't needed; https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#internals
          version: v2.7.2
          # only run on changed files in this PR / push
          only-new-issues: true